- package-lock.json
- package.json
- server/routes/install-routes.js
- shared/ArchiveView.js
- shared/hydrogen-vm-render-script.js
- vite.config.js
Update to work with latest `hydrogen-view-sdk@0.0.12` after there has been months of changes.
Also nice to develop with the SDK now that https://github.com/vector-im/hydrogen-web/pull/693 has merged.
> Update to work with latest `hydrogen-view-sdk@0.0.12`

- server/start-dev.js
Organize `start-dev` file and add more `nodemon` logging
Spawned from https://github.com/vitejs/vite/issues/8492
> Organize `start-dev` file and add more `nodemon` logging

- server/lib/config.js
Explain how `config` inherits: command line -> environment variables -> `config/config-{env}.json`
> Explain how `config` inherits: command line -> environment variables -> `config/config-{env}.json`

- README.md
- test/README.md
Better explain how to get the project and tests to run at this point
> Better explain how to get the project and tests to run at this point

- .github/workflows/containerize.yaml
- Dockerfile
- docker-health-check.js
- server/lib/fetch-endpoint.js
- server/routes/install-routes.js
Make sure container is able to start up.
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/22
```
docker build -t matrix-public-archive .
docker run -d -p3053:3050 --env matrixServerUrl=http://FAKE_SERVER/ --env matrixAccessToken=FAKE_TOKEN matrix-public-archive
```
---
https://stackoverflow.com/questions/42737957/how-to-view-docker-compose-healthcheck-logs
```
docker inspect --format "{{json .State.Health }}" wizardly_mcclintock
```
> Make sure container is able to start up

- server/fetch-events-in-range.js
Fix archive not responding in big rooms because homeserver times out on `/context` request (too much state).
Add `filter={"lazy_load_members":true}` so that `/context` responds without timing out by returning just the state for the sender of the included event. Otherwise, the homeserver returns all state in the room at that point in time which in big rooms, can be 100k member events that we don't care about anyway. Synapse seems to timeout at about the ~5k state event mark.
Without `filter={"lazy_load_members":true}`, Synapse can only handle ~4k member events (probably state in general) before `/context` times out before it ever responds in the 180 second window. I'm only looking at the member count as a rough proxy but the number of member events + state will be more.
Loads | Member …
> Fix archive not responding in big rooms because homeserver times out on `/context` request

- server/server.js
Enable tracing by config so we can enable from argv, env variable, or config file
> Enable tracing by config so we can enable from argv, env variable, or config file

- README.md
Add app screenshot
`.../!OvgDmYaPOFRRWnIdQe:half-shot.uk/date/2021/08/06`
`npm run test-interactive`
> Add app screenshot

- server/routes/install-routes.js
- server/routes/prevent-clickjacking-middleware.js
Add clickjacking prevention middleware
Fix https://github.com/matrix-org/matrix-public-archive/issues/67
> Add clickjacking prevention middleware

- .github/workflows/linting.yml
- .github/workflows/tests.yaml
- .prettierignore
- shared/views/NotEnoughEventsFromDaySummaryTileView.js
- shared/views/RoomCardView.js
Add linting to CI:
- Prettier
- ESLint
> Add linting to CI

- server/hydrogen-render/render-hydrogen-to-string-unsafe.js
Fix XSS when blatting `window.matrixPublicArchiveContext` to the page
Fix https://github.com/matrix-org/internal-config/issues/1335
> Fix XSS when blatting `window.matrixPublicArchiveContext` to the page

- package-lock.json
- package.json
- server/routes/room-directory-routes.js
- shared/lib/archive-history.js
- shared/room-directory-vm-render-script.js
- shared/viewmodels/RoomDirectoryViewModel.js
- shared/views/RoomDirectoryView.js
- test/e2e-tests.js
Page-load with the correct homeserver selected (according to `?homeserver`).
Fix https://github.com/matrix-org/matrix-public-archive/issues/92
Also makes sure that the `?homeserver` is always available somewhere in the list; whether that be in the available homeserver list or the added homeserver list depending on it someone cleared it out or never had it because they visited from someone else's link.
> Page-load with the correct homeserver selected

- shared/views/RoomDirectoryView.js
Fix typo in room fetch error section
> Fix typo in room fetch error section

- shared/views/RoomDirectoryView.js
Fixup room directory fetch error message
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/96
> Fixup room directory fetch error message

- server/routes/room-routes.js
Add comment reference to issue about adding hour chunk time slices
> Add comment reference to issue about adding hour chunk time slices

- config/config.default.json
- server/routes/room-directory-routes.js
- server/routes/room-routes.js
Add config to disable search engine indexing
Fix https://github.com/matrix-org/matrix-public-archive/issues/116
> Add config to disable search engine indexing

- shared/viewmodels/ArchiveRoomViewModel.js
Fix NPE with non-existent event permalink `?at=$doesnotexist`
Fix https://github.com/matrix-org/matrix-public-archive/issues/129
> Fix NPE with non-existent event permalink `?at=$doesnotexist`

- package-lock.json
- package.json
Update Hydrogen SDK dependency `0.23.0-scratch`
> Update Hydrogen SDK dependency `0.23.0-scratch`

- README.md
- config/config.default.json
Update readme with creature comforts and MSC3030-enabled server prerequisite
Spawning from https://github.com/matrix-org/matrix-public-archive/issues/142
> Update readme with creature comforts and MSC3030-enabled server prerequisite

- README.md
Fix: #140 
Badge source used: https://shields.io/
> Link our Matrix room from the readme

- README.md
Link to demo videos and TWIM blog posts that describe show-off the project
Fix #150
> Link to demo videos #150

- README.md
Update readme to reflect more fleshed out actuality
> Update readme to reflect more fleshed out actuality

- package-lock.json
- package.json
Move `escape-string-regexp` to a normal dep since we use it on the server
> Move `escape-string-regexp` to a normal dep since we use it on the server

- README.md
Prefer tracing documentation linked below
> Prefer tracing documentation linked below

- build-scripts/vite.config.js
- client/js/entry-client-timeout.js
- server/hydrogen-render/render-page-html.js
- server/middleware/timeout-middleware.js
- server/routes/client-side-room-alias-hash-redirect-route.js
Fix styles on timeout page since we started using the [`manifest.json` for asset paths](https://github.com/matrix-org/matrix-public-archive/pull/175).
> Fix styles on timeout page

- server/child-process-runner/run-in-child-process.js
Expose child errors that only occur in `stderr` log output.
Who knows why we can't capture these errors via the more conventional `child.on('error', (err) => { })` listener 🤷 
```
RethrownError: Failed to render Hydrogen to string. In order to reproduce, feed in these arguments into `renderHydrogenToString(...)`:
renderHydrogenToString arguments: { ... }
at renderHydrogenToString (server/hydrogen-render/render-hydrogen-to-string.js:58:11)
--- Original Error ---
RethrownError: Child process exited with code 1
at assembleErrorAfterChildExitsWithErrors (server/child-process-runner/run-in-child-process.js:60:29)
--- Original Error ---
No child errors
```
```
RethrownError: Failed to render Hydrogen to string. In order to reproduce, feed in these arguments into `renderHydrogenToString(...)`: …
```
> Expose child errors that only occur in `stderr` log output

- shared/views/TimeSelectorView.js
Protect from no `IntersectionObserver` while SSR
Same thing we do in https://github.com/matrix-org/matrix-public-archive/blob/f3318446f8b71e2e43329ac599ac33f548835169/shared/views/ArchiveRoomView.js#L178-L180
> Protect from no `IntersectionObserver` while SSR

- server/hydrogen-render/render-page-html.js
- server/lib/matrix-utils/fetch-room-data.js
- server/routes/room-routes.js
- shared/lib/check-text-for-nsfw.js
- shared/viewmodels/RoomDirectoryViewModel.js
- test/e2e-tests.js
Mark NSFW room pages with `<meta name="rating" content="adult">`
- https://developers.google.com/search/docs/crawling-indexing/safesearch
- https://developers.google.com/search/docs/crawling-indexing/special-tags
> Mark NSFW room pages with `<meta name="rating" content="adult">`

- CHANGELOG.md
Add changelog and prepare with initial `v0.1.0` release
> Add changelog and prepare with initial `v0.1.0` release

- server/middleware/timeout-middleware.js
Fix mistake in config access for `workaroundCloudflare504TimeoutErrors`
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/228
> Fix mistake in config access for `workaroundCloudflare504TimeoutErrors`

- package-lock.json
- package.json
Update to `vite@4.3.9` while debugging some unrelated issues
Still good to have the latest fixes in any case
> Update to `vite@4.3.9` while debugging some unrelated issues

- server/lib/matrix-utils/fetch-room-data.js
- server/routes/room-routes.js
- shared/hydrogen-vm-render-script.js
- shared/viewmodels/ArchiveRoomViewModel.js
- shared/views/RightPanelContentView.js
Indicate when the room was set to `world_readable` and by who
> Indicate when the room was set to `world_readable` and by who
