package-lock.json
package.json

We use `vite@2.9.6` because `vite>=2.9.7` is interfering with `nodemon`, see https://github.com/vitejs/vite/issues/8492
This means that when using `npm run start-dev` -> [`start-dev.js`](https://github.com/matrix-org/matrix-public-archive/blob/40f9d2ea5afb74c4f04030fb1a643fcd803a70e7/server/start-dev.js), `nodemon` wasn't restarting when a change was made.

Fix `nodemon` not being able to watch for changes because `vite` is interfering 

---

server/routes/install-routes.js

Use new Hydrogen light-theme asset (`hydrogen-view-sdk/assets/theme-element-light.css`) directly instead of legacy `style.css`

Use new Hydrogen light-theme asset directly instead of legacy `style.css`

---

public/styles/styles.css

Remove extra body margin causing offset from viewport
Before (hard to see but notice extra white space at top) | After
--- | ---

Remove extra body margin causing offset from viewport

---

README.md

Easy get the app running steps:
1. Install
1. Edit the config to point at your homeserver
1. Run the app!
---
This is made possible thanks to the change we made in https://github.com/matrix-org/matrix-public-archive/pull/20#discussion_r897567619 to start using a scoped custom version of `hydrogen-view-sdk`. This includes all of the scratch changes necessary to get this project running which makes the `npm install` just work out of the box without all of the `npm link` hassle.

Easy get the app running steps

---

.github/workflows/containerize.yaml
.github/workflows/tests.yaml
Dockerfile
package.json
test/dockerfiles/synapse/log_config.yaml

Containerize app (make a Docker image for `matrix-public-archive`)
```
ghcr.io/matrix-org/matrix-public-archive/matrix-public-archive
```
... with a variety of tags!
- https://github.com/orgs/matrix-org/packages?tab=packages&q=matrix-public-archive

Containerize app (make a Docker image for `matrix-public-archive`)

---

Dockerfile

Fix image not running in K8s (ROSA)
Trying to solve the container exiting with error code `243`. `npm` throws `243` for any command you try to run with it.
Here is how to get into the container while the entrypoint normally errors.
```
$ oc run -i --tty --image=ghcr.io/matrix-org/matrix-public-archive/matrix-public-archive:sha-65edaea1a9713bb2cc93fa98638327fdeff765cd mpa-test2 --port=3050 --restart=Never --env="DOMAIN=cluster" --command /bin/bash
$ npm start
$ echo $?
243
```
Why does the same image work in Docker?
```
$ docker run -it --entrypoint /bin/bash ghcr.io/matrix-org/matrix-public-archive/matrix-public-archive:sha-65edaea1a9713bb2cc93fa98638327fdeff765cd
$ npm start
```
Seems like it could be either of these issues. Both are `8.6.0`+ problems as well which lines up with the …

Fix image not running in K8s (ROSA)

---

server/fetch-events-in-range.js
test/client-utils.js
test/e2e-tests.js

Remove unneeded `include_redundant_members` from `/messages` `filter` and add tests to ensure member state is still visible.
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/28#discussion_r909428366
Notice the purple user avatar and display name set.
`npm run test-interactive` -> diverse messages test

Remove unneeded `include_redundant_members` from `/messages` `filter` and test that member state is still visible

---

package-lock.json
package.json
test/e2e-tests.js

Use stable test selectors
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/29#discussion_r909492946
---
Updated Hydrogen to add the consistent `data-testid` attribute selectors,
https://github.com/vector-im/hydrogen-web/pull/773
```
npm install hydrogen-view-sdk@npm:@mlm/hydrogen-view-sdk@0.0.13-scratch
```

Use stable test selectors from Hydrogen (`data-testid`)

---

server/hydrogen-render/1-render-hydrogen-to-string.js
server/hydrogen-render/2-render-hydrogen-to-string-fork-script.js

Fix large option payloads throwing `E2BIG` and `ENAMETOOLONG` errors
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/36

Fix large option payloads throwing E2BIG and ENAMETOOLONG

---

server/hydrogen-render/1-render-hydrogen-to-string.js
server/hydrogen-render/2-render-hydrogen-to-string-fork-script.js
server/hydrogen-render/3-render-hydrogen-to-string-unsafe.js

Make sure we finish sending the HTML payload before we exit the process.
I encountered a page which responded successfully but all of the Hydrogen HTML was missing. It just had the boilerplate around it.
What I am guessing happened is that since `process.send` is async, with a sufficiently large
payload and race condition, `process.exit(0)` was being called before it finished sending.
Related:
- https://stackoverflow.com/questions/34627546/process-send-is-sync-async-on-nix-windows
- https://github.com/nodejs/node/commit/56d9584a0ead78874ca9d4de2e55b41c4056e502
- https://github.com/nodejs/node/issues/6767

Make sure we finish sending the HTML payload before we exit the process

---

server/fetch-events-in-range.js
server/fetch-room-data.js
server/hydrogen-render/1-render-hydrogen-to-string.js
server/tracing/trace-utilities.js

Manually instrument some archive logic so we get nice labeled spans of what's happening in the app (OpenTelemetry tracing).
Before | After
--- | ---
**Update:** Tracking all of this information in https://github.com/matrix-org/matrix-public-archive/issues/49
In https://github.com/matrix-org/matrix-public-archive/pull/36, we started wrapping our whole rendering Hydrogen `vm` flow in a `child_process` because using a Node.js `vm` context doesn't have a way to stop the process (it just keeps running). With the `child_process` we can kill it when we choose after we get the HTML result.
Now with this timing, we can also get some insight into how bad of a performance hit having to run the hydrogen render in the `child_process` is. It seems to be a lot slower: ~50ms vs 360ms.
```js
// Use the …
```

Manually instrument some archive logic so we get nice labeled spans of what's happening in the app (OpenTelemetry tracing).

---

server/ensure-room-joined.js
server/fetch-events-in-range.js
server/routes/install-routes.js
shared/lib/url-creator.js
test/README.md
test/client-utils.js
test/e2e-tests.js

Add test for joining a new federated room and making sure the messages are available (homeserver should backfill).
Synapse changes: https://github.com/matrix-org/synapse/pull/13205, https://github.com/matrix-org/synapse/pull/13320
```
docker build -t matrixdotorg/synapse -f docker/Dockerfile .
```

Add test for joining a new federated room

---

config/config.default.json
server/hydrogen-render/1-render-hydrogen-to-string.js
server/hydrogen-render/2-render-hydrogen-to-string-fork-script.js
server/hydrogen-render/3-render-hydrogen-to-string-unsafe.js
server/lib/rethrown-error.js
server/routes/install-routes.js

Make the `child_process` error catching more robust
Split off from https://github.com/matrix-org/matrix-public-archive/pull/43
Listen to `process.on('uncaughtException', ...)` and handle the async errors ourselves so it no longer fails the child process.
And if the process does exit with status code 1 (error), we have those underlying errors serialized and shown.
---
In the future, maybe we want to switch away from `child_process`, https://github.com/matrix-org/matrix-public-archive/issues/49, which would also be nice to remove all of this complexity.

Make the `child_process` error catching more robust

---

config/config.default.json
config/config.test.json
package-lock.json
package.json
server/lib/config.js

Use JSON5 for configuration files with comments. Now we can leave the available config in `config.default.json` without having to add weird instructions to remove the `xxx`, etc
- https://www.npmjs.com/package/json5
- https://www.npmjs.com/package/nconf
- https://github.com/indexzero/nconf/issues/113#issuecomment-69999413

Use JSON5 for configuration files with comments

---

LICENSE.md
package.json

Add Apache 2.0 license.
I don't want to add the standard copyright header to every file that other projects have though.

Add Apache 2.0 license

---

shared/lib/assert.js

Better assertion error language: `AssertionError: expected ${value} to be truthy`

Better assertion error language

---

public/styles/styles.css
server/routes/install-routes.js
server/routes/timeout-middleware.js
shared/4-hydrogen-vm-render-script.js
shared/ArchiveView.js
shared/CalendarView.js
shared/lib/archive-history.js

Make the archive responsive

---

package-lock.json
package.json
shared/4-hydrogen-vm-render-script.js

Fix missing `room.observePowerLevels()` throwing error after render.
```
Uncaught (in promise) TypeError: this._room.observePowerLevels is not a function
at RoomViewModel2._recreateComposerOnPowerLevelChange (matrix-public-archive.js:23498:53)
at new RoomViewModel2 (matrix-public-archive.js:23469:14)
at mountHydrogen (matrix-public-archive.js:27131:25)
at matrix-public-archive.js:27174:1
```
Doesn't affect main-line rendering but the error is annoying to see. More Hydrogen boilerplate 😞

Fix missing `room.observePowerLevels()` throwing error after render

---

server/routes/install-routes.js
shared/4-hydrogen-vm-render-script.js

Fix `DisabledComposerView` description being overriden by powerlevel changes
We added the description in https://github.com/matrix-org/matrix-public-archive/pull/54 but then made a fix to one of the after render errors, https://github.com/matrix-org/matrix-public-archive/pull/57, which exposed that the description is then overriden when the powerlevel changes.
We now just override the getters directly instead of the internal fields which are overwritten internally.
---
This also fixes a warning from Hydrogen in the console:
```
disposable not found, did it leak? {kind: 'disabled', description: Array(3)}
```

Fix `DisabledComposerView` description being overriden by powerlevel changes

---

server/lib/matrix-utils/fetch-events-in-range.js
server/lib/matrix-utils/fetch-public-rooms.js
server/lib/matrix-utils/timestamp-to-event.js
server/routes/room-routes.js
test/e2e-tests.js

Redirect to last day with message history: `/:roomIdOrAlias` -> `/:roomIdOrAlias/date/:yyyy/:mm/:dd`
Fix https://github.com/matrix-org/matrix-public-archive/issues/60

Redirect to last day with message history

---

server/hydrogen-render/render-hydrogen-vm-render-script-to-page-html.js
server/lib/matrix-utils/ensure-room-joined.js
server/lib/matrix-utils/fetch-room-data.js
server/lib/status-error.js
server/routes/room-routes.js
test/client-utils.js
test/e2e-tests.js

Only show `world_readable` or `public` rooms in the archive. Only allow `world_readable` rooms to be indexed by search engines.
Related to https://github.com/matrix-org/matrix-public-archive/issues/47

Only show `world_readable` or `public` rooms in the archive. Only index `world_readable`

---

public/css/room-directory.css

Bigger more clickable buttons on mobile. Feels a lot better on a phone. The buttons already have invisible margin in their hitbox but the bigger size makes your thumb less cramped to the edge to click them.
Also reduce the container padding so it feels more balanced in the single column card layout.

Bigger more clickable buttons on mobile

---

public/css/room-directory.css
public/js/entry-client-hydrogen.js
public/js/entry-client-room-directory.js
server/lib/matrix-utils/fetch-public-rooms.js
server/lib/status-error.js
server/routes/room-directory-routes.js
server/routes/room-routes.js
shared/hydrogen-vm-render-script.js
shared/lib/url-creator.js
shared/room-directory-vm-render-script.js
shared/viewmodels/RoomDirectoryViewModel.js
shared/views/RoomCardView.js
shared/views/RoomDirectoryView.js
test/client-utils.js
test/e2e-tests.js

Add search to room directory landing page
Part of https://github.com/matrix-org/matrix-public-archive/issues/6
**Update:** Created a spec issue to suggest a possible solution: https://github.com/whatwg/html/issues/8284
Autocomplete sucks. Since we're using a common `<input type="search" name="search">`, we get a lot of unrelated autocomplete suggestions. For example, Amazon's order history search box uses this same pattern so I see a bunch of results from it. If it was `name="q"`, you would see a lot of GitHub search results, etc.
There doesn't seem to be a way to scope the suggestions to the app's domain.
The only resource I can find talking about this problem is from https://stackoverflow.com/questions/60838558/how-to-improve-browser-autocomplete-suggestions-without-turning-them-off …

Add search to room directory landing page

---

package-lock.json
package.json
public/css/styles.css
server/hydrogen-render/render-hydrogen-to-string.js
server/hydrogen-render/render-hydrogen-vm-render-script-to-page-html.js
server/lib/matrix-utils/fetch-events-from-timestamp-backwards.js
server/lib/matrix-utils/fetch-events-in-range.js
server/routes/room-routes.js
server/start-dev.js
shared/hydrogen-vm-render-script.js
shared/lib/assert.js
shared/lib/custom-tile-utilities.js
shared/lib/url-creator.js
shared/viewmodels/ArchiveRoomViewModel.js
shared/viewmodels/ArchiveViewModel.js
shared/viewmodels/CalendarViewModel.js
shared/viewmodels/DeveloperOptionsViewModel.js
shared/viewmodels/NotEnoughEventsFromDaySummaryTileViewModel.js
shared/views/ArchiveRoomView.js
shared/views/ArchiveView.js
shared/views/DeveloperOptionsView.js
shared/views/NotEnoughEventsFromDaySummaryTileView.js
shared/views/RightPanelContentView.js
test/client-utils.js
test/e2e-tests.js

Add surrounding messages to the given messages so we have a full screen of content to make it feel lively even in quiet rooms
As you scroll around the timeline across different days, the date changes in the URL, calendar, etc
Add summary item to the bottom of the timeline that explains if we couldn't find any messages in the specific day requested 
No events on day | No events at all
--- | ---
Also allows you to the jump to the next activity in the room. Adds `/:roomId/jump?ts=xxx&dir=[f|b]` to facilitate this.
Part of https://github.com/matrix-org/matrix-public-archive/issues/46
Add developer options modal which is linked from the bottom of the right-panel
- Adds an option so you can debug the `IntersectionObserver` and how it's selecting the active day from the top-edge of the scroll …

Show surrounding messages for a full screen of content

---

server/tracing/tracing.js

Add domain to tracing service to distinguish different Matrix public archive instances

Add domain to tracing service to distinguish different Matrix public archive instances

---

server/hydrogen-render/render-hydrogen-to-string.js

Sanity check that we are not leaking the access token to the client.
This isn't spawning from any previous security issue. Just adding an extra check to help ensure we don't ever regress this in the future.
```
AssertionError [ERR_ASSERTION]: We should not be leaking the `config.matrixAccessToken` to the Hydrogen render function because this will reach the client!
at renderHydrogenToString (matrix-public-archive\server\hydrogen-render\render-hydrogen-to-string.js:24:3)
at renderHydrogenVmRenderScriptToPageHtml (matrix-public-archive\server\hydrogen-render\render-hydrogen-vm-render-script-to-page-html.js:22:36)
at matrix-public-archive\server\routes\room-directory-routes.js:53:28
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

Sanity check that we are not leaking the access token to the client

---

server/routes/timeout-middleware.js

Fix wrong path to Hydrogen styles on timeout error page.
Regressed in https://github.com/matrix-org/matrix-public-archive/pull/61 where we tried to serve this under `/css/hydrogen-styles.css` but it doesn't work because all of the image and font references in the CSS file expect it to be at the domain root so just reverted back to serving at the root `/`.

Fix wrong path to Hydrogen styles on timeout error page

---

server/routes/room-directory-routes.js

Throw more understandable error when we fail to fetch from the homeserver room directory
Fix https://github.com/matrix-org/matrix-public-archive/issues/80
```
RethrownError: Unable to fetch rooms from room directory (homeserver=http://localhost:8008/)
searchTerm=, paginationToken=undefined, limit=9
at matrix-public-archive\server\routes\room-directory-routes.js:55:13
--- Original Error ---
Error: HTTP Error Response: 500 Internal Server Error: {"errcode":"M_UNKNOWN","error":"Internal server error"}
URL=http://localhost:8008/_matrix/client/v3/publicRooms?
at checkResponseStatus (matrix-public-archive\server\lib\fetch-endpoint.js:21:11)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
at async fetchEndpoint (matrix-public-archive\server\lib\fetch-endpoint.js:38:3)
at …
```

Throw more understandable error when we fail to fetch from the homeserver room directory

---

shared/views/CalendarView.js

Fix off-by-one calendar months with time zones that are greater than UTC+0 (GMT+0).
Fix https://github.com/matrix-org/matrix-public-archive/issues/77
Previously, we would calculate `lastDayOfTheMonthDate` in the local timezone because we were using the vanilla `new Date(year, month, 0)` constructor. For any timezone greater than `UTC+0` (like London UTC+1 or Korea UTC +9), this means that the date is a day-behind when we go back to UTC+0.
**Before:**
```
inputDate Fri, 29 Jul 2022 00:00:00 GMT 1659052800000
lastDayOfTheMonthDate Sat, 30 Jul 2022 23:00:00 GMT 1659222000000
lastDayOfTheMonth 30
```
**After**
```
inputDate Fri, 29 Jul 2022 00:00:00 GMT 1659052800000
lastDayOfTheMonthDate Sun, 31 Jul 2022 00:00:00 GMT 1659225600000
lastDayOfTheMonth 31
```
It would be nice to be able to …

Fix off-by-one calendar months with time zones that are greater than UTC+0

---

public/css/room-directory.css

Improve performance of scrolling on room directory (animating gradient and shadow header).
1. Dumbs down the drop shadow to not be as intensive (really helps performance)
1. Put the header content on its own layer above the animating background which is probably easier for the browser to composite together
1. Make the bounds of the header contents smaller so the layer is smaller
1. Specifying `overflow: hidden;` on the header seemed to be an extra gain probably because the drop shadows were really spilling over before
Before, I experienced laggy stutter on mobile (Pixel 4a) and even on a Macbook Pro. Was fine on a chonky desktop computer with GPU though 😁
Now it seems buttery smooth ⏩

Improve performance of scrolling on room directory (animating gradient and shadow header)

---

server/hydrogen-render/render-hydrogen-to-string-unsafe.js
server/hydrogen-render/render-hydrogen-to-string.js
server/hydrogen-render/render-hydrogen-vm-render-script-to-page-html.js
server/routes/content-security-policy-middleware.js
server/routes/install-routes.js
server/routes/room-directory-routes.js
server/routes/room-routes.js
server/routes/timeout-middleware.js

Add `Content-Security-Policy` (CSP) that restricts the page to just what it is expected to do.
This helps limit the damage that can be done by any XSS attack.
Fix https://github.com/matrix-org/internal-config/issues/1341

Add `Content-Security-Policy` (CSP)

---

public/css/room-directory.css
public/css/styles.css
server/routes/room-directory-routes.js
shared/room-directory-vm-render-script.js
shared/viewmodels/RoomDirectoryViewModel.js
shared/views/HomeserverSelectionModalContentView.js
shared/views/RoomDirectoryView.js

Load room directory and show error message when we're unable to fetch rooms
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/84 to address https://github.com/matrix-org/matrix-public-archive/issues/80
Also explains why we show the details of the error message.
Part of https://github.com/matrix-org/internal-config/issues/1342
Related to https://github.com/matrix-org/matrix-public-archive/issues/97
<blockquote>
This may be a temporary problem with the homeserver where the room directory lives (foo.bar) or the homeserver that the archive is pulling from (my.synapse.server). You can try adjusting your search term or select a different homeserver to look at. If this problem persists, please open a [bug report](https://github.com/matrix-org/matrix-public-archive/issues/new) …

Load room directory and show error message when we're unable to fetch rooms

---

shared/lib/archive-history.js

Fix hash and query parameter ordering and repeating
This would happen after opening the "Add server" modal
Before:
```
/?search=&homeserver=foo.bar#/add-server?search=&homeserver=foo.bar
```
After:
```
/?search=&homeserver=foo.bar#/add-server
```

Fix hash and query parameter ordering and repeating

---

shared/views/RoomDirectoryView.js

Stop using `selectEl.value` as crutch over swapping `selected` attribute
Related context: https://github.com/WebReflection/linkedom/issues/171#issuecomment-1287334938
Originally introduced in:
- https://github.com/matrix-org/matrix-public-archive/pull/87
- https://github.com/matrix-org/matrix-public-archive/pull/98

Stop using `selectEl.value` as crutch over swapping `selected` attribute

---

shared/viewmodels/RoomDirectoryViewModel.js

Fix pagination links not accounting for homeserver selection
Fix https://github.com/matrix-org/matrix-public-archive/issues/93
Previously caused the `?homeserver` query parameter to be lost when paginating

Fix pagination links not accounting for homeserver selection

---

shared/viewmodels/RoomDirectoryViewModel.js

Link rooms with `?via` query parameter from room directory landing page
Fix https://github.com/matrix-org/matrix-public-archive/issues/91
So we're always able to join the room from our origin homeserver to the remote room we don't know about yet.

Link rooms with `?via` query parameter from room directory landing page

---

shared/views/RoomDirectoryView.js

Fix form `<select>` value not being up to date by the time we auto-submit the form on selection
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/102#discussion_r1002190782
Before | After (`foo.bar` in URL after we just added it)
--- | ---

Fix form `<select>` value not being up to date by the time we auto-submit the form on selection

---

shared/lib/archive-history.js
shared/views/ModalView.js

Clean up spurious logs when SSR Hydrogen
**Before:**
```
Child printed something to stdout: Mounting Hydrogen...
Child printed something to stderr: Skipping `addedHomservers` read from LocalStorage since LocalStorage is not available
Child printed something to stdout: Completed mounting Hydrogen: 22.188ms
Child printed something to stdout: 2 uncaughtException TypeError: this.dialogNode.close is not a function
at ModalView.closeModal (C:\Users\MLM\Documents\GitHub\element\matrix-public-archive\shared\views\ModalView.js:115:21)
at Timeout._onTimeout (C:\Users\MLM\Documents\GitHub\element\matrix-public-archive\shared\views\ModalView.js:87:18)
at listOnTimeout (node:internal/timers:559:17)
at processTimers (node:internal/timers:502:7)
```
**After:**
```
Child printed something to stdout: …
```

Clean up spurious logs when SSR Hydrogen

---

shared/lib/archive-history.js

Fix URL being duplicated in query param
Fix https://github.com/matrix-org/matrix-public-archive/pull/104#discussion_r1004023030
We were previously seeing this behavior with the old code:
```
Before: http://localhost:3050/!xxx:server/date/2022/09/20?via=my.synapse.server
replaceUrlSilently(url='http://localhost:3050/!xxx:server/date/2022/09/20')`
After: http://localhost:3050/!xxx:server/date/2022/09/20?via=my.synapse.serverhttp://localhost:3050/!xxx:server/date/2022/07/29
```
Because `replacingUrl` was evaluating to `replacingUrl = '?via=my.synapse.serverhttp://192.168.1.151:3050/!HBehERstyQBxyJDLfR:my.synapse.server/date/2022/07/29'` which is relative and was appended to the current URL.
Now with the new code, we more clearly handle the 3 cases:
- Normal Hydrogen `#/foo-bar` hash routing …

Fix URL being duplicated in query param

---

package-lock.json
server/lib/matrix-utils/ensure-room-joined.js
server/lib/matrix-utils/fetch-events-from-timestamp-backwards.js
server/lib/matrix-utils/fetch-room-data.js
server/lib/matrix-utils/timestamp-to-event.js
server/routes/install-routes.js
server/routes/redirect-to-correct-archive-url-if-bad-sigil-middleware.js
server/routes/room-routes.js
shared/hydrogen-vm-render-script.js
shared/lib/url-creator.js
shared/viewmodels/ArchiveRoomViewModel.js
shared/viewmodels/CalendarViewModel.js
shared/viewmodels/DeveloperOptionsContentViewModel.js
shared/viewmodels/ModalViewModel.js
shared/viewmodels/NotEnoughEventsFromDaySummaryTileViewModel.js
shared/viewmodels/RoomDirectoryViewModel.js
shared/views/DeveloperOptionsContentView.js
test/client-utils.js
test/e2e-tests.js

Add support for room aliases. Also does friendly redirects if you don't exactly use the right URL pattern. For example, if you paste the full room ID with the `!` like `/roomid/!foo:bar`, it will properly redirect you to `/roomid/foo:bar`. It also does this sort of thing for URL encoded room ID's and aliases.
Fix https://github.com/matrix-org/matrix-public-archive/issues/25
> [...] we can use a schemaless [Matrix URI (`matrix://`)](https://github.com/matrix-org/matrix-spec-proposals/pull/2312/files) which doesn't include the sigils so there is no URL encoding issue.
> 
> The URL's for the archive end up looking like:
> 
>  - Room alias: `/r/matrix:matrix.org/date/2022/06/28`
>  - Room ID: `/roomid/OGEhHVWSdvArJzumhm:matrix.org/date/2022/06/28`
- We can't test room alias honest mistakes …

Add support for room aliases

---

build/build-client-scripts.js
public/css/room-directory.css
public/js/entry-client-room-alias-hash-redirect.js
server/routes/client-side-room-alias-hash-redirect-route.js
server/routes/install-routes.js
shared/lib/redirect-if-room-alias-in-hash.js
shared/room-directory-vm-render-script.js
shared/viewmodels/RoomDirectoryViewModel.js
shared/views/RoomDirectoryView.js

Add support for client-side room alias hash `#` redirects to the correct URL. This helps when someone just pastes a room alias on the end of the domain,
- `/#room-alias:server` -> `/r/room-alias:server`
- `/r/#room-alias:server/date/2022/10/27` -> `/r/room-alias:server/date/2022/10/27`
Since these redirects happen on the client, we can't write any e2e tests. Those e2e tests do everything but run client-side JavaScript.
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/107
Part of https://github.com/matrix-org/matrix-public-archive/issues/25
From the room directory: `/#room-alias:server` -> `/r/room-alias:server`
From the room archive view: `/r/#room-alias:server/date/2022/10/27` -> `/r/room-alias:server/date/2022/10/27`
`/#room-alias:server` -> `/r/room-alias:server` | …

Add support for client-side room alias hash `#` redirects to the correct URL

---

public/css/styles.css
shared/hydrogen-vm-render-script.js
shared/viewmodels/ArchiveRoomViewModel.js
shared/views/ArchiveRoomView.js

Refactor to use `TimelineView`. We have to figure out our own layout but does get rid of some of the `RoomView` boilerplate. The `TimelineView` still has outside boilerplate styles to work.
There shouldn't be any visible change:
environment | Before | After
--- | --- | ---
desktop | ![](https://user-images.githubusercontent.com/558581/199236829-6f882c59-7b30-4ea6-b547-817dc04fc815.png) | ![](https://user-images.githubusercontent.com/558581/199236799-97d40752-ec66-496b-8436-6017602e90e1.png)
mobile (right-panel collapsed) | ![](https://user-images.githubusercontent.com/558581/199237019-9a5f70da-69cf-4faa-94b2-ce137cdf2383.png) | ![](https://user-images.githubusercontent.com/558581/199237196-5216b673-bfa1-4281-bbee-5765daf3f28a.png)
mobile (right-panel expanded) | …

Refactor to use `TimelineView`

---

shared/hydrogen-vm-render-script.js
shared/viewmodels/ArchiveRoomViewModel.js
shared/views/ArchiveRoomView.js

Move Hydrogen `timelineViewModel` creation to our main view model.
Was it better to keep this Hydrogen boilerplate outside? Maybe 🤷. It's possible that all of this will go away with something like https://github.com/MadLittleMods/hydrogen-static-archives-prototype/pull/2
Should we also move the [`room` VM creation](https://github.com/matrix-org/matrix-public-archive/blob/8275f120a68cae5a1c888c93cb0906c8393f1e3e/shared/hydrogen-vm-render-script.js#L88-L111)? Maybe but it's not as much noise as all of this tile/timeline stuff.

Move Hydrogen `timelineViewModel` creation to our main view model

---

config/config.default.json
package-lock.json
package.json
public/css/styles.css
server/lib/fetch-endpoint.js
server/lib/matrix-utils/fetch-events-from-timestamp-backwards.js
server/lib/matrix-utils/get-messages-response-from-event-id.js
server/routes/room-routes.js
shared/hydrogen-vm-render-script.js
shared/lib/custom-tile-utilities.js
shared/lib/url-creator.js
shared/viewmodels/ArchiveRoomViewModel.js
shared/viewmodels/JumpToNextActivitySummaryTileViewModel.js
shared/viewmodels/JumpToPreviousActivitySummaryTileViewModel.js
shared/views/ArchiveRoomView.js
shared/views/JumpToNextActivitySummaryTileView.js
shared/views/JumpToPreviousActivitySummaryTileView.js
test/e2e-tests.js
test/lib/client-utils.js
test/lib/test-error.js

Add a way to jump forwards and backwards to more activity in the room (seamless navigation<sup>1</sup>).
Fix https://github.com/matrix-org/matrix-public-archive/issues/46
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/71
Summary:
- Changes the "Jump to next activity in room" to actually continue you to the next 100 messages ahead. Previously, it only jumped you to the single next event in the room which meant a lot of backwards overlap each time.
- Jumping this direction will also start your scroll position at the top of the timeline to continue reading seamlessly `?continue=top`
- Adds "Jump to previous activity in room" to the top of the timeline to continue reading the previous part of the conversation.
[1]: There is a caveat with seamless here which is also …

Add a way to jump forwards and backwards to more activity in the room (seamless navigation)

---

shared/viewmodels/ArchiveRoomViewModel.js

Don't change the URL as you scroll around in the timeline.
Fix https://github.com/matrix-org/matrix-public-archive/issues/115
Reverting behavior originally introduced in https://github.com/matrix-org/matrix-public-archive/pull/71

Don't change the URL as you scroll around

---

server/lib/fetch-endpoint.js
server/lib/matrix-utils/ensure-room-joined.js
server/lib/matrix-utils/fetch-public-rooms.js
server/lib/matrix-utils/fetch-room-data.js
server/lib/matrix-utils/get-messages-response-from-event-id.js
server/lib/matrix-utils/timestamp-to-event.js
test/e2e-tests.js
test/lib/client-utils.js

Refactor `fetchEndpointAsText`/`fetchEndpointAsJson` to return `res` alongside `data`
Split out of https://github.com/matrix-org/matrix-public-archive/pull/121
where we needed to use `res.url`.

Refactor `fetchEndpointAsText`/`fetchEndpointAsJson` to return `res` alongside `data`

---

package-lock.json
package.json
shared/hydrogen-vm-render-script.js
shared/room-directory-vm-render-script.js
shared/viewmodels/ArchiveRoomViewModel.js

Updates to be compatible with the latest Hydrogen changes (rename `urlCreator` -> `urlRouter`)
Hydrogen changes:
- https://github.com/vector-im/hydrogen-web/pull/918

Updates to be compatible with the latest Hydrogen changes (rename `urlCreator` -> `urlRouter`)

---

package-lock.json
package.json
server/routes/install-routes.js

This change enables CORS support in the archive — to allow web developers to create web applications with frontend JavaScript code that can fetch pages from the archive (for example, for scraping content from chat logs).
Otherwise, without this change, web developers can’t create web apps with frontend JavaScript that can fetch chat logs from the archive and then consume the content of the logs.
It’s imaginable that web developers may find use cases for consuming the chat logs in the archive from frontend JavaScript code — at the simplest level, web apps that fetch and scrape logs to get data out of them or to pull out particular snippets from the logs.
Developers can anyway already scrape the contents of the archive — by using server-side programming languages or by using `curl` or …

Enable CORS support

---

server/lib/matrix-utils/timestamp-to-event.js

Relates to this issue:
- #142
Perhaps some of the README edits (and a default config comment) can be backed out or reworded that are part of this PR...
- #144
... but I'll leave it to someone who can word it better.

Switch `/timestamp_to_event` endpoint to stable v1 #142

---

README.md
config/config.default.json

Update docs to reflect that we need stable MSC3030 /timstamp_to_event
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/154

Update docs to reflect that we need stable MSC3030 `/timstamp_to_event`

---

server/lib/matrix-utils/ensure-room-joined.js
server/lib/matrix-utils/get-server-name-from-matrix-room-id-or-alias.js
server/lib/parse-via-servers-from-user-input.js
server/routes/room-routes.js
test/server/matrix-utils/get-server-name-from-matrix-room-id-or-alias-tests.js

Do our best to get the user to the right place and try joining `via` derived server name
Split out from https://github.com/matrix-org/matrix-public-archive/pull/167

Do our best to get the user to the right place and try joining `via` derived server name

---

server/lib/set-headers-to-preload-assets.js
server/routes/room-directory-routes.js
server/routes/room-routes.js

Add preload link headers for downstream [Cloudflare early hints](https://developers.cloudflare.com/cache/about/early-hints/). 
Because it takes us at best several seconds to request information from a homeserver and then server-side render the page, the browser has to wait for the response before it can even try loading the necessary assets. With this change that facilitates early hints, the browser can preload all of the assets necessary before we are done generating the response and will be ready to go by the time we're all done on the server.
Fix https://github.com/matrix-org/matrix-public-archive/issues/32
Part of https://github.com/matrix-org/matrix-public-archive/issues/132
Tracking actually enabling early hints in Cloudflare in the deployment issue: …

Add preload link headers for downstream Cloudflare early hints (assets download before the page is rendered)

---

server/routes/client-side-room-alias-hash-redirect-route.js
server/routes/install-routes.js
server/routes/room-directory-routes.js
server/routes/room-routes.js
server/routes/timeout-middleware.js

Serve Hydrogen assets from `/hydrogen-assets/` sub-directory for easier targeting of cache rules
Fix https://github.com/matrix-org/matrix-public-archive/issues/160

Serve Hydrogen assets from `/hydrogen-assets/` sub-directory for easier targeting of cache rules

---

.eslintrc.json
build-scripts/.eslintrc.json
client/js/.eslintrc.json
client/js/entry-client-hydrogen.js
client/js/entry-client-room-alias-hash-redirect.js
client/js/entry-client-room-directory.js
package-lock.json
package.json
server/lib/get-dependencies-for-entry-point-name.js
server/lib/get-favicon-asset-urls.js
server/start-dev.js
test/.eslintrc.json

Migrate from `eslint-plugin-node` to `eslint-plugin-n`
Spawning originally from [.. ](https://github.com/matrix-org/matrix-public-archive/pull/177) where https://github.com/mysticatea/eslint-plugin-node/issues/255 was useful.
~~But we seem to be trading for a new problem -> https://github.com/eslint-community/eslint-plugin-n/issues/75~~

Migrate from `eslint-plugin-node` to `eslint-plugin-n`

---

server/child-process-runner/run-in-child-process.js
server/hydrogen-render/render-hydrogen-to-string.js

Only `require.resolve(...)` the path once.
Perhaps an early optimization or not even needed but doesn't seem wise to keep pulling this over and over (best case it's cached).

Only `require.resolve(...)` the path once

---

build-scripts/vite.config.js
server/hydrogen-render/render-page-html.js
server/lib/get-dependencies-for-entry-point-name.js
server/start-dev.js

Fix scripts not loading from the [production ready build PR](https://github.com/matrix-org/matrix-public-archive/pull/175).
We don't have tests for the client-side UI interactions and I didn't properly test myself since the page looked good.
We need to use the `file` part from the `manifest.json` and prepend `/` so the path always starts from the root.
Change from `<script type="text/javascript"> to `<script type="module">`
```
Uncaught ReferenceError: exports is not defined
at hydrogen.cjs.js:34:25
```
- `build.commonjsOptions.transformMixedEsModules`
- https://vitejs.dev/config/build-options.html#build-commonjsoptions
- https://github.com/rollup/plugins/tree/master/packages/commonjs#transformmixedesmodules
- `optimizeDeps.include`: https://vitejs.dev/guide/dep-pre-bundling.html
- …

Fix scripts not loading from the production ready build PR

---

server/start-dev.js

Make sure to restart the server after Vite `manifest.json` changes so it can pick up the latest and serve pages correctly.

Make sure to restart the server after Vite `manifest.json` changes

---

server/lib/set-headers-to-preload-assets.js

Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/171 and https://github.com/matrix-org/matrix-public-archive/pull/175 where they broke because we went from scripts to modules.
Part of https://github.com/matrix-org/matrix-public-archive/issues/132
Before this PR, we were seeing these warning in the Chrome devtools console:
```
A preload for 'foo' is found, but is not used because the request credentials mode does not match. Consider taking a look at crossorigin attribute.
```
This is caused by a credentials mode mismatch between the `<script type="module">` tag and the `Link` header. A `<script type="module">` with no `crossorigin` attribute indicates a credentials mode of `omit` and a naive `Link: </foo-url>; rel=preload; as=script;` has a  default credentials mode of …

Fix preload link headers

---

build-scripts/vite.config.js

Make sure we still convert from CommonJS to ESM even when symlinking `hydrogen-view-sdk` locally
- https://github.com/rollup/plugins/tree/master/packages/commonjs#usage-with-symlinks
- https://vitejs.dev/config/shared-options.html#resolve-preservesymlinks
- https://github.com/vitejs/vite/issues/2405 -> https://github.com/vitejs/vite/pull/4708/files
- https://rollupjs.org/configuration-options/#preservesymlinks

Make sure we still convert from CommonJS to ESM even when symlinking `hydrogen-view-sdk` locally

---

package-lock.json
package.json
shared/hydrogen-vm-render-script.js

Update with latest Hydrogen changes `0.26.0-scratch` - 2023-04-26
Spawning from https://github.com/matrix-org/matrix-public-archive/pull/187#discussion_r1177644014
Of note:
- Adds date headers, https://github.com/vector-im/hydrogen-web/pull/938
- Add "Copy matrix.to permalink" message action, https://github.com/vector-im/hydrogen-web/pull/921
- Removes `?v=3.13` query parameters from Inter font references in CSS, https://github.com/vector-im/hydrogen-web/pull/961
- This is what we need to solve https://github.com/matrix-org/matrix-public-archive/pull/187#discussion_r1177638781
```
cd hydrogen-web
yarn build:sdk
cd target
Edit `target/package.json` to `@mlm/hydrogen-view-sdk@^0.26.0-scratch`
npm publish
```

Update Hydrogen SDK dependency `0.26.0-scratch` - 2023-04-26

---

server/lib/get-dependencies-for-entry-point-name.js
server/lib/set-headers-to-preload-assets.js

Preload fonts and images
Part of https://github.com/matrix-org/matrix-public-archive/issues/132

Preload fonts and images

---

server/routes/room-routes.js

Link prior art and reasoning why we still always join before using the Matrix API's
See https://github.com/matrix-org/matrix-public-archive/issues/50

Link prior art and reasoning why we still always join before using the Matrix API's

---

server/hydrogen-render/render-page-html.js
server/lib/get-dependencies-for-entry-point-name.js
server/lib/get-favicon-asset-urls.js

Cache derived info from the `manifest.json`:
- Like getting all of the dependencies for a given entry point
- And the favicons
Also fix the problem where `server/hydrogen-render/render-page-html.js` was calling `getFaviconAssetUrls()` right away before the client build had a chance to generate `dist/manifest.json` and result in `Error: Cannot find module '../../dist/manifest.json'`

Cache derived info from the `manifest.json`

---

build-scripts/vite.config.js

Add note that files in `public/` is copied as-is

Add note that files in `public/` is copied as-is

---

shared/viewmodels/RoomDirectoryViewModel.js

Fix typos where I misspelled `homserver` -> `homeserver`
Spawning from another typo that [@pdurbin pointed out in the docs](https://github.com/matrix-org/matrix-public-archive/pull/194#discussion_r1178510694).

Fix typos where I misspelled "homeserver"

---

shared/views/ArchiveRoomView.js

Don't jump calendar around for events which appear in the future compared to the timestamp in the URL.
This sort of situation occurs often for Gitter imported historical rooms where we have a bunch of history that is timestamp massaged intermixed with a bunch of join events which we couldn't timestamp massage at the time.
Fix https://github.com/matrix-org/matrix-public-archive/issues/182
Before | After
--- | ---
http://192.168.1.149:3050/r/gitter-imported-history-ts-massaging:my.synapse.server/date/2022/05/05

Don't jump calendar around for events which appear in the future

---

shared/hydrogen-vm-render-script.js

Fix broken links with the [`matrix-media-repo`](https://github.com/turt2live/matrix-media-repo) because there are too many slashes
Before:
```
http://localhost:8008//_matrix/media/r0/thumbnail/my.synapse.server/abcde?width=30&height=30&method=crop
```
After:
```
http://localhost:8008/_matrix/media/r0/thumbnail/my.synapse.server/abcde?width=30&height=30&method=crop
```
The extra slash seems to work fine with the built-in media repo in Synapse but noticed broken links when using `matrix.org` which delegates to the `matrix-media-repo`

Fix broken links with the `matrix-media-repo` because there are too many slashes

---

docs/faq.md

Note differentiation from `view.matrix.org` with day-by-day navigation

Note differentiation from `view.matrix.org` with day-by-day navigation

---

server/tracing/tracing.js

We can better detect static assets to avoid tracing nowadays because all assets are served from `/assets` since https://github.com/matrix-org/matrix-public-archive/pull/175

We can better detect static assets to avoid tracing nowadays

---

client/css/room-directory.css
package-lock.json
package.json
shared/lib/local-storage-keys.js
shared/room-directory-vm-render-script.js
shared/viewmodels/AvatarViewModel.js
shared/viewmodels/DeveloperOptionsContentViewModel.js
shared/viewmodels/RoomCardViewModel.js
shared/viewmodels/RoomDirectoryViewModel.js
shared/views/RoomCardView.js
shared/views/RoomDirectoryView.js
test/dockerfiles/Synapse.Dockerfile
test/e2e-tests.js

Add safe search filter for NSFW rooms
Alternative community PR (unfinished): https://github.com/matrix-org/matrix-public-archive/pull/155
Fix https://github.com/matrix-org/matrix-public-archive/issues/89
- On one-hand, it would be nice for NSFW-tolerant people to be able to link to room directory as they see it. This would also solve the flash of blocked to unblocked when the page loads.
- On the other hand, it allows people to just fling people to some nasty content although they could just link the room anyway.
- In any case, it's simpler not to do this for now and we can iterate when people actually speak up with an actual need/use-case.

Add safe search filter for NSFW rooms

---

server/lib/set-headers-for-date-temporal-context.js
server/lib/set-headers-to-preload-assets.js
server/routes/room-routes.js
test/e2e-tests.js

Set `X-Date-Temporal-Context: [past|present|future]` header for easy cache rules:
- Cache `past` things heavily
- Cache `present`/`future` things for 5 minutes
This accomplishes the goal we set out for:
> - We can cache all responses except for the latest UTC day (and anything in the future). ex. `/!aMzLHLvScQCGKDNqCB:gitter.im/date/2022/10/13`
>    - For the latest day, we could set the cache expire after 5 minutes or so
>
> *-- [Matrix Public Archive deployment issue](https://github.com/vector-im/sre-internal/issues/2079)*
And this way we don't have to do any fancy date parsing and comparison from the URL which is probably not even possible Cloudflare cache rules.

Set `X-Date-Temporal-Context` header for easy cache rules

---

server/routes/room-routes.js
shared/hydrogen-vm-render-script.js
shared/viewmodels/ArchiveRoomViewModel.js
test/e2e-tests.js

Fix time selector showing when less than the page limit of messages
Fix https://github.com/matrix-org/matrix-public-archive/issues/211

Fix time selector showing when less than the page limit of messages

---

server/hydrogen-render/render-page-html.js
server/middleware/timeout-middleware.js
server/routes/client-side-room-alias-hash-redirect-route.js
server/routes/room-directory-routes.js
server/routes/room-routes.js

Add some `<meta name="description" ...>` to pages. 
Not the best but probably better than the default (a good first iteration)
Part of https://github.com/matrix-org/matrix-public-archive/issues/202
- https://developers.google.com/search/docs/appearance/snippet

Add some `<meta name="description" ...>` to pages

---

README.md
docs/faq.md

Various updates to put `archive.matrix.org` in the forefront
Fix https://github.com/matrix-org/matrix-public-archive/issues/212
README rendered from this branch: https://github.com/matrix-org/matrix-public-archive/blob/madlittlemods/improve-readme-with-archive.matrix.org/README.md
Screenshot at 90% zoom with even dimensions for better scaling

Various updates to put `archive.matrix.org` in the forefront

---

shared/viewmodels/DeveloperOptionsContentViewModel.js

Fix `debugActiveDateIntersectionObserver` checkbox being checked by default when the value was actually `null`. Now we properly only care about explicit `'true'`, `'false'` from local storage.
Before | After
--- | ---
Before:
```
<input id="debugActiveDateIntersectionObserver" type="checkbox" checked="null">
```
After:
```
<input id="debugActiveDateIntersectionObserver" type="checkbox">
```

Fix `debugActiveDateIntersectionObserver` checkbox being checked by default when the value was actually `null`

---

server/routes/room-routes.js

Better grammar in URL preview description
Part of https://github.com/matrix-org/matrix-public-archive/issues/202
Before | After
--- | ---

Better grammar in URL preview description

---

package-lock.json
package.json

Update Hydrogen SDK to include MXC URL's on media
Useful in moderation scenarios where you want to quarantine media and can quickly/easily look at the data attribute on the media (image/videos). Or simply write a little script to extract all of the `data-mxc-url` and `data-thumbnail-mxc-url` attributes.
ex.
```
```

Update Hydrogen SDK to include MXC URL's on media

---

config/config.default.json
server/middleware/timeout-middleware.js

Prevent Cloudflare from overriding our own 504 timeout page
Explored in https://gitlab.matrix.org/matrix-public-archive/deployment/-/issues/2 (internal deployment issue)
> Cloudflare returns an Cloudflare-branded HTTP 502 or 504 error when your origin web server responds with a standard HTTP 502 bad gateway or 504 gateway timeout error:
>
> *-- https://developers.cloudflare.com/support/troubleshooting/cloudflare-errors/troubleshooting-cloudflare-5xx-errors/#502504-from-your-origin-web-server*
The only way to disable this functionality is to have an Enterprise Cloudflare plan and use the `Enable Origin Error Pages` option:
> **Enable Origin Error Pages**
>
> When Origin Error Page is set to “On”, Cloudflare will proxy the 502 and 504 error pages directly from the origin.
>
> Requires …

Prevent Cloudflare from overriding our own 504 timeout page

---

shared/lib/check-text-for-nsfw.js
test/shared/lib/check-text-for-nsfw-tests.js

Catch NSFW rooms with underscores
`\b` includes `_` which is a bit unexpected since we expect a room that looks like `NSFW_foo` to be caught in safe search

Catch NSFW rooms with underscores

---

server/start-dev.js

Document why changes to locally linked `hydrogen-view-sdk` don't trigger a rebuild

Document why changes to locally linked `hydrogen-view-sdk` don't trigger a rebuild

---

docs/faq.md

Add context and demystify public/world_readable/guest/peeking in the FAQ
Spawning from:
- https://github.com/matrix-org/matrix-public-archive/issues/47#issuecomment-1568698809
- https://matrix.to/#/!SzoPnANsRYxITaDPaJ:matrix.org/$Zwr_GzklOjhRoAY-D9Ekh0qYhZYUWI_d5HUcJ1180zM?via=matrix.org&via=evulid.cc&via=t2l.io
- https://matrix.to/#/!QQpfJfZvqxbCfeDgCj:matrix.org/$ZKgZ6oPhW39gByfORAxp-zfL_g6lISL73Ms_6D16SPQ?via=matrix.org&via=element.io&via=envs.net
- https://matrix.to/#/!SzoPnANsRYxITaDPaJ:matrix.org/$eC8O8zFwsvEkoy2kdwrNowKhvCg_kCU7zZhjSlSEGto?via=matrix.org&via=evulid.cc&via=t2l.io

Add context and demystify public/world_readable/guest/peeking in the FAQ

---

client/css/styles.css
client/img/external-link-icon.svg
shared/views/RightPanelContentView.js

Link [FAQ about indexing](https://github.com/matrix-org/matrix-public-archive/blob/main/docs/faq.md#how-do-i-opt-out-and-keep-my-room-from-being-indexed-by-search-engines) in the right-panel footer so people can more easily understand what goes into the result and find [issues to track about opting out](https://github.com/matrix-org/matrix-public-archive/issues/47).
> This room is not being indexed by search engines ([more info](https://github.com/matrix-org/matrix-public-archive/blob/main/docs/faq.md#how-do-i-opt-out-and-keep-my-room-from-being-indexed-by-search-engines)).
> This room is being indexed by search engines ([more info](https://github.com/matrix-org/matrix-public-archive/blob/main/docs/faq.md#how-do-i-opt-out-and-keep-my-room-from-being-indexed-by-search-engines)).

Link FAQ about indexing in the right-panel footer.

---

shared/viewmodels/RoomDirectoryViewModel.js

Fix Firefox sorting room cards in the wrong direction. They will now sort by room members descending (highest to lowest) as expected. 
Fix https://github.com/matrix-org/matrix-public-archive/issues/218
The `/publicRooms` (room directory) endpoint already returns rooms in the correct order which is why we didn't care about the order before but the different `[].sort(...)` implementations in browsers necessitates we be explicit about it. Ideally, we wouldn't have to use the `ObservableMap.sortValues()` method at all but it seems like one of the only ways to get the values out. In any case, maybe it's more clear what order things are in now.
This bug stems from the fact that `[1, 2, 3, 4, 5].sort((a, b) => 1)` returns different results in Chrome vs Firefox (found from …

Fix Firefox sorting room cards in the wrong direction

---

docs/faq.md
server/lib/matrix-utils/ensure-room-joined.js
test/e2e-tests.js

Add reason why the archive bot is joining the room
Using the join `reason` added in [MSC2367](https://github.com/matrix-org/matrix-spec-proposals/pull/2367). Unfortunately, this PR doesn't have much effect because it doesn't look like many clients support it yet (Element doesn't support it for example).
Part of https://github.com/matrix-org/matrix-public-archive/issues/257

Add reason why the archive bot is joining the room

---

server/routes/install-routes.js

Add `/faq` -> https://github.com/matrix-org/matrix-public-archive/blob/main/docs/faq.md redirect
Part of https://github.com/matrix-org/matrix-public-archive/issues/257 so we can set the display name of the bot to `archive.matrix.org/faq` and people can read about the project is about and why the bot joined.

Add `/faq` redirect

---

server/hydrogen-render/render-hydrogen-to-string-unsafe.js
server/hydrogen-render/render-page-html.js
server/middleware/timeout-middleware.js
server/routes/client-side-room-alias-hash-redirect-route.js
server/routes/room-directory-routes.js
server/routes/room-routes.js

Use `rel=canonical` link to de-duplicate event permalinks
Fix https://github.com/matrix-org/matrix-public-archive/issues/251
> if multiple pages are only differentiated by a query argument and contain the exact same set of messages with only tiny changes (such as in its highlighting or in its preview metadata), they should be linked back together to a single canonical URL. A search engine crawler is free to throw away any and all alternative links which fold back to the same canonical one instead of indexing each of them separately.

Use `rel=canonical` link to de-duplicate event permalinks

---

server/lib/matrix-utils/ensure-room-joined.js

Prevent join event spam with stable `reason`.
In the case of someone visiting a room via an alias, we can't get access to the `room_id` before we join the room. I've opted to just point to the Matrix Public Archive instance in general. This way the `join` reason is always stable regardless how someone is visiting the room.
Fix https://github.com/matrix-org/matrix-public-archive/issues/267
Join `reason` was originally added in https://github.com/matrix-org/matrix-public-archive/pull/262

Prevent join event spam with stable `reason`

---

server/routes/room-routes.js

Prefer canonical room alias in `rel=canonical` link
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/266
Part of https://github.com/matrix-org/matrix-public-archive/issues/251

Prefer canonical room alias in `rel=canonical` link

---

server/lib/matrix-utils/fetch-room-data.js
server/routes/room-directory-routes.js
server/routes/room-routes.js
test/e2e-tests.js

Only `world_readable` can be considered as opting into having history publicly on the web. Anything else must not be ~~archived~~ viewable without login until there's a dedicated state event for opting into archiving.
See #47

Don't allow previewing `shared` history rooms

---

package.json

Fix eslint trying to look at `node_modules/`. I'm not sure what exactly is causing the behavior change now besides that I am running on Linux.
The quote fix around the path is from https://stackoverflow.com/questions/51021751/express-js-lint-gives-mistake
`node_modules/` is already part of our `.eslintignore`
https://github.com/matrix-org/matrix-public-archive/blob/1d3e930fbd57788ed60494a64835127ff97dbd53/.eslintignore#L1
Previously:
```sh
$ npm run lint
> matrix-public-archive@0.1.0 lint
> eslint **/*.js
Oops! Something went wrong! :(
ESLint: 8.37.0
You are linting "node_modules/ipaddr.js", but all of the files matching the glob pattern "node_modules/ipaddr.js" are ignored.
If you don't want to lint these files, remove the pattern "node_modules/ipaddr.js" from the list of arguments …
```

Fix eslint trying to look at `node_modules/`

---

docs/faq.md

Update FAQ to explain `world_readable` only
Follow-up to https://github.com/matrix-org/matrix-public-archive/pull/239

Update FAQ to explain `world_readable` only

---

shared/lib/check-text-for-nsfw.js
test/shared/lib/check-text-for-nsfw-tests.js

Fix `18+` false positives with NSFW check
Was noticing false positives with our test room names like: `planet-1688081266353-room-18`
**Before:**
```regex
/(\b|_)18+(\b|_)/i
```
**After:**
```regex
/(\b|_|-|\s|^)18\+(\b|_|-|\s|$)/i
```
https://www.debuggex.com/
```
npm run test -- --grep "checkTextForNsfw"
```

Fix `18+` false positives with NSFW check

---

test/e2e-tests.js

Try and make the seamless pagination test more robust (wait for Synapse to settle)
Previously was seeing some failures like this locally
```
1 failing
1) matrix-viewer
Matrix Viewer
Room directory
pagination is seamless:
AssertionError [ERR_ASSERTION]: Make sure we saw all visible rooms paginating through the directory
+ expected - actual
"planet-1689366398300-room-29"
"planet-1689366398300-room-31"
"planet-1689366398300-room-32"
"planet-1689366398300-room-34"
-  "planet-1689366398300-room-34"
"planet-1689366398300-room-35"
"planet-1689366398300-room-37"
"planet-1689366398300-room-38"
"planet-1689366398300-room-4"
at Context.<anonymous> (test/e2e-tests.js:2835:16)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

Try and make the seamless pagination test more robust (wait for Synapse to settle)
